server:
  port: 8081

spring:
  application:
    name: producer-service

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection:
      mode: connection

myapp:
  rabbitmq:
    template:
#      exchange: directExchangeTest
#      exchange-type: direct
#      routing-key: testKey

      exchange: fanoutExchangeTest
      exchange-type: fanout
      routing-key:
#
#      exchange: topicExchangeTest
#      exchange-type: topic
#      routing-key: testKey

