server:
  port: 8081

spring:
  application:
    name: producer-service

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 5
    template:
      exchange: exchangeTest
#      exchange-type: "direct"
      exchange-type: "fanout"
#      exchange-type: "topic"
